spring:
  rabbitmq:
    username: rabbit
    password: senha
  data:
    mongodb:
      host: localhost
      port: 27017
      database: profiles
      authentication-database: admin
      username: root
      password: rootpassword

logging:
  level:
    br:
      nofraud: debug