spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: profiles
      authentication-database: admin
      username: root
      password: rootpassword
  rabbitmq:
    username: rabbit
    password: senha
server:
  port: 8011
logging:
  level:
    br:
      nofraud: debug